{
 "title": "ddd",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Current System State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AQ Level ",
   "type": "stat",
   "description": "0 → Good (green)\n\n1 → Moderate (yellow)\n\n2 → Poor (orange)\n\n3 → Hazardous (red)",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"aq_level\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "Confidence",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"confidence\")\n  |> last()\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))\n"
    }
   ]
  },
  {
   "title": "Anomaly Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: -5m)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"is_anomaly\")\n  |> last()\n"
    }
   ]
  },
  { "title": "Raw Sensor Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Humidity vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"hum\")"
    }
   ]
  },
  {
   "title": "Gas (MQ) vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"mq\")\n"
    }
   ]
  },
  {
   "title": "Temperature vs Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"temp\")"
    }
   ]
  },
  { "title": "Engineered Features", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Anomaly Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) => r._field == \"anomaly_score\")\n"
    }
   ]
  },
  {
   "title": "Gas Normalization & Rolling Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"aq\")\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r._measurement == \"air_quality\")\n  |> filter(fn: (r) =>\n    r._field == \"gas_norm\" or\n    r._field == \"rolling_mean_10\"\n  )\n"
    }
   ]
  }
 ]
}